# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7418709ceb779ef0e5bf632d75887b37d2d77b0d7046077ec5d5da010b5a013b8df3a51f14dfb3edf98e477c9cf3a0c4c8b28dd167d22e50155c72f94ab6874

test:
  secret_key_base: abee15395a5137116b6dc8cd9d4b63d9c012eeb5161ba096c95abbd056fc69c0385377a50860f95426087eec4bd99bc061659fb49eee6c72cb74b402e1d2a897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
